sudo: required
services:
    - docker
    
before_install:
    - docker build -t sirocco1987/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sirocco1987/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "Docker-env"
    bucket_name:
    bucket_path: "docker-react"
    on:
       branch: master
