sudo: required
services:
    - docker
    
before_install:
    - docker build -t sirocco1987/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sirocco1987/docker-react npm run test


