sudo: required
services:
    - docker
    
before_install:
    - docker build -t sirocco1987/docker-react -f Dockerfile.dev .

script:
    - docker run sirocco1987/docker-react npm run test -- --coverage
